services:
  postgres:
    image: postgres:17.6
    container_name: postgres_db
    environment:
      POSTGRES_DB: colaboration_system_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/schemas:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
